### ISSUE TITLE
[minor] Circuit Connector sprites not drawn correctly

### ISSUE THREAD

**Issue by Nexela** [judos/beltSorter#11]
Lemme know when you get tired of seeing my name pop up :+1: 

Pop down a belt-sorter in an area with no power.
belt-sorter has visible circuit connector sprite -- Should not be able to see them here unless connected via red/green wire.

add Power to the belt-sorter
belt-sorter circuit-connector disappears and lights up green

connect belt-sorter with red or green wire
no circuit connector appears -- At this point one would expect to see them :)

**Comment by judos** [comment]
Haha no worries :D feel free to open pull requests by the way, your suggestions and hints in the previous issues were very good.
As for this issue I currently have no clue. I use a proxy item which is always connected to the belt by a circuit cable. That allows me to show the beltSorter as green and running when no condition is set even though it is day (the entity works like the lamp and during day it would be disabled when no condition is set). So the proxy item always has a condition (iron-plate something iron-plate). When no condition is set on the actual belt sorter I change the operator on this proxy item to "=" which shows then also the green overlay patch.
However why the cricuit connector shows in some cases and in some not I have no clue.
I would propose not to investigate it too much since I would rather implement another awesome feature which I didn't have time for up to now ;) Is that fine for you? If you find out anything more about this feel free to notice me.

**Comment by Nexela** [comment]
I have some ideas that can fix all three issues, I will shoot over a PR if I get a chance to work on it.
