### ISSUE TITLE
error with running the event handler:

### ISSUE THREAD

**Issue by MFeltmann1** [judos/beltSorter#6]
i placed the sorter and a sec later it gave me that message
image of error.
http://imgur.com/a/2lBZu

**Comment by judos** [comment]
Hi, I can't really reproduce your issue without the following information:
- factorio version
- beltSorter version
- other mods used if any
I must guess this is already fixed with the newest beltSorter version 0.2.2.

Please reopen if that doesn't happen to be the case and give me some more information

**Comment by MFeltmann1** [comment]
it is fixed in the updated version
