### ISSUE TITLE
Bug - Outgoing belts won't join to output

### ISSUE THREAD

**Issue by eranor** [judos/beltSorter#9]
Hi. 
I don't know if it is a bug or just a technical limitation of the prototype object you are using, but when I put a belt to the sorter to output on a belt that is perpendicular to the side it's on, it does not rotate like it would with a belt. Is it possible to fix this?
The items are placed fine, but it's a little ugly.
![Example](http://puu.sh/qMMfI/9e98537325.jpg)
Thanks in advance.

**Comment by judos** [comment]
I'm afraid currently this is not possible to implement. I tried spawning invisible belts below the beltSorter to make the output belts connect virtually. But that only works for 1 belt, not for all.
For the moment I opened an interface request such that factorio would allow me to do this:
https://forums.factorio.com/viewtopic.php?f=33&t=32474

**Comment by Nexela** [comment]
I managed to get it to work in 2 directions but even that was hacky. There might be some more things I can do and if I get a chance I will look into it.

**Comment by judos** [comment]
@Nexela, nice how did you do that?

**Comment by Nexela** [comment]
https://gist.github.com/Nexela/db22f443b2222b038d9a8248afb194a9

**Comment by judos** [comment]
Seems like it's only either horizontal or vertical, but it won't consider both directions...

**Comment by judos** [comment]
Talked shortly with Rseding91 from factorio dev team. Short sum up: This behavior can't be changed easily since the whole transport-belt code would have to be rewritten. Therefore it won't be done.

<judos> Rseding91, would it be possible to have an api to let belts connect to an entity?
<Rseding91> no
<Rseding91> That's not just a switch I can flip. The entire infrastructure for belts would have to be re-written from the ground up and would loose a lot of performance in the process.
<judos> Rseding91, that I can believe for sure, and somehow change the check when belts will connect to existing belts (if multiples are on one tile) ? :P
<Rseding91> Belts can't be built on the same tile.
<Rseding91> The game won't allow it.

**Comment by Nexela** [comment]
<Rseding91> Belts can't be built on the same tile.
not %100 accurate :)

![sorter](https://cloud.githubusercontent.com/assets/13972192/18455710/ad305db8-7919-11e6-96e5-8ed77a4668d6.png)

**Comment by judos** [comment]
Well at least in the base game I know it's not possible.
So tell me how you got this image? :stuck_out_tongue:

**Comment by Nexela** [comment]
Through a fundamental hack

(probably didnt have to do this part)
cloned fast-underground-belt as belt-sorter-belt2
changed north and south create entity to belt2

This still had the same "problem"

second thing I did was manually put a west-east belt on the north tile and south tile, popped the sorter in between them then added the east and west belts

This gives me hope that it can be done!  Possibly by changing the size of the hidden undergrounds.

**Comment by Nexela** [comment]
Option 243a.:

on_built_entity 
type belt
if belt next to sorter and direction create fakebelt to make connection...

**Comment by judos** [comment]
And then check whether it still works if 3 belts are "output" in any possible placing order. Hmm I will check it again.
